spec:
  meshExpansion:
    onboarding:
      localRepository: {}
      endpoint:
        hosts:
          - vm-onboarding.tetrate.prod
        secretName: vm-onboarding
      workloads:
        authentication:
          jwt:
            issuers:
            - issuer: https://issuer-a.tetrate.prod
              shortName: ubuntu-vm-a
              tokenFields:
                attributes:
                  jsonPath: .custom_attributes
              jwks: |
                ${JWKS_VM_A}
            - issuer: https://issuer-b.tetrate.prod
              shortName: ubuntu-vm-b
              tokenFields:
                attributes:
                  jsonPath: .custom_attributes
              jwks: |
                ${JWKS_VM_B}
            - issuer: https://issuer-c.tetrate.prod
              shortName: ubuntu-vm-c
              tokenFields:
                attributes:
                  jsonPath: .custom_attributes
              jwks: |
                ${JWKS_VM_C}