---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: client
  namespace: default
  labels:
    app: client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2023-12-11T14:07:30Z"
  labels:
    app: client
  name: client
  namespace: default
spec:
  selector:
    matchLabels:
      app: client
  strategy: {}
  template:
    metadata:
      creationTimestamp: "2023-12-11T14:07:30Z"
      labels:
        app: client
    spec:
      serviceAccountName: client
      containers:
      - args:
        - server
        image: fortio/fortio
        name: fortio-client
        ports:
        - containerPort: 8080
        - containerPort: 42422
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  creationTimestamp: "2023-12-11T14:07:30Z"
  labels:
    app: client
  name: client
  namespace: default
spec:
  ports:
  - port: 8080
    targetPort: 0
  selector:
    app: client
status:
  loadBalancer: {}
