---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Tier1Gateway
metadata:
  organization: tetrate
  tenant: prod
  workspace: gw-tier1-ws
  group: gw-tier1-group
  name: gw-tier1-abc
spec:
  displayName: AppABC_Tier1GW
  workloadSelector:
    namespace: gateway-tier1
    labels:
      app: gw-tier1-abc
  externalServers:
  - name: abc-https
    hostname: abc.demo.tetrate.io
    port: 443
    tls:
      mode: SIMPLE
      secretName: app-abc-certs
    clusters:
    - name: active-cluster
    - name: standby-cluster
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: IngressGateway
metadata:
  organization: tetrate
  tenant: prod
  workspace: gw-abc-ws
  group: gw-abc-group
  name: gw-ingress-abc
spec:
  displayName: AppABC_IngressGW
  workloadSelector:
    namespace: gateway-abc
    labels:
      app: gw-ingress-abc
  http:
  - name: abc
    hostname: abc.demo.tetrate.io
    port: 80
    routing:
      rules:
      - route:
          host: ns-a/app-a.ns-a.svc.cluster.local
          port: 80
