---
apiversion: api.tsb.tetrate.io/v2
kind: Workspace
metadata:
  organization: tetrate
  tenant: prod
  name: abc
spec:
  displayName: Application_ABC
  namespaceSelector:
    names:
      - "*/gateway-abc"
      - "*/ns-a"
      - "*/ns-b"
      - "*/ns-c"
---
apiVersion: api.tsb.tetrate.io/v2
kind: WorkspaceSetting
metadata:
  organization: tetrate
  tenant: prod
  workspace: abc
  name: abc-setting
spec:
  defaultEastWestGatewaySettings:
    - workloadSelector:
        namespace: gateway-abc
        labels:
          app: gw-eastwest-abc
      exposedServices:
      - serviceLabels:
          app: app-a
          service: app-a
      - serviceLabels:
          app: app-b
          service: app-b
      - serviceLabels:
          app: app-c
          service: app-c
---
apiversion: api.tsb.tetrate.io/v2
kind: Workspace
metadata:
  organization: tetrate
  tenant: prod
  name: tier1
spec:
  displayName: Shared_Infra_Tier1
  namespaceSelector:
    names:
      - "demo/gateway-tier1"
