---
apiVersion: install.tetrate.io/v1alpha1
kind: ManagementPlane
metadata:
  name: managementplane
  namespace: tsb
spec:
  hub: $TSB_INSTALL_REPO_URL
  organization: $TSB_ORGANIZATION
  dataStore:
    postgres:
      host: $POSTGRES_HOST
      port: $POSTGRES_PORT
      name: $POSTGRES_DB_NAME
  telemetryStore:
    elastic:
      host: $ELASTIC_HOST
      port: $ELASTIC_PORT
      version: $ELASTIC_VERSION
      selfSigned: true
      protocol: https
  identityProvider:
    ldap:
      host: $LDAP_HOST
      port: $LDAP_PORT
      search:
        baseDN: dc=tetrate,dc=io
      iam:
        matchDN: "cn=%s,ou=People,dc=tetrate,dc=io"
        matchFilter: "(&(objectClass=person)(uid=%s))"
      sync:
        usersFilter: "(objectClass=person)"
        groupsFilter: "(objectClass=groupOfUniqueNames)"
        membershipAttribute: uniqueMember
  # Customize token issuer to use signing key that you have created before.
  tokenIssuer:
    jwt:
      expiration: 8760h
      issuers:
      - name: https://jwt.tetrate.io
        # Signing key stored in Kubernetes secret.
        signingKey: private.key
      # Kubernetes secret name where you store IAM signing key.
      signingKeysSecret: iam-signing-key
  components:
    internalCertProvider:
      certManager:
        managed: INTERNAL