apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  selector:
   matchLabels:
    app: pgadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin4
          image: dcagatay/pwless-pgadmin4
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: tsb
            - name: POSTGRES_PASSWORD
              value: tsb-postgres-password
            - name: POSTGRES_HOST
              value: postgres.tsb.svc.cluster.local
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "tsb"
          ports:
            - containerPort: 80
              name: pgadminport
          volumeMounts:
            - name: servers-json
              subPath: servers.json
              mountPath: /pgadmin4/servers.json
            - name: pgpass
              subPath: pgpass
              mountPath: /pgadmin4/pgpass
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 256Mi
      volumes:
        - name: servers-json
          configMap:
            name: servers.json
        - name: pgpass
          configMap:
            name: pgpass
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  clusterIP: None
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: pgadmin
  publishNotReadyAddresses: true
  sessionAffinity: None
  type: ClusterIP
