---
apiversion: api.tsb.tetrate.io/v2
kind: Workspace
metadata:
  organization: tetrate
  tenant: prod
  name: app-d-ws
spec:
  displayName: AppD_WS
  namespaceSelector:
    names:
      - "*/ns-d"
---
apiversion: api.tsb.tetrate.io/v2
kind: Workspace
metadata:
  organization: tetrate
  tenant: prod
  name: app-e-ws
spec:
  displayName: AppE_WS
  namespaceSelector:
    names:
      - "*/ns-e"
---
apiversion: api.tsb.tetrate.io/v2
kind: Workspace
metadata:
  organization: tetrate
  tenant: prod
  name: app-f-ws
spec:
  displayName: AppF_WS
  namespaceSelector:
    names:
      - "*/ns-f"
---
apiversion: api.tsb.tetrate.io/v2
kind: Workspace
metadata:
  organization: tetrate
  tenant: prod
  name: gw-def-ws
spec:
  displayName: GatewayDEF_WS
  namespaceSelector:
    names:
      - "*/gateway-def"
---
apiversion: api.tsb.tetrate.io/v2
kind: Workspace
metadata:
  organization: tetrate
  tenant: prod
  name: gw-tier1-ws
spec:
  displayName: GatewayTier1_WS
  namespaceSelector:
    names:
      - "demo/gateway-tier1"
