---
apiVersion: traffic.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: prod
  workspace: app-d-ws
  name: app-d-traffic-group
spec:
  displayName: AppD_TrafficGroup
  namespaceSelector:
    names:
      - "*/ns-d"
  configMode: BRIDGED
---
apiVersion: security.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: prod
  workspace: app-d-ws
  name: app-d-security-group
spec:
  displayName: AppD_SecurityGroup
  namespaceSelector:
    names:
      - "*/ns-d"
  configMode: BRIDGED
---
apiVersion: traffic.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: prod
  workspace: app-e-ws
  name: app-e-traffic-group
spec:
  displayName: AppE_TrafficGroup
  namespaceSelector:
    names:
      - "*/ns-e"
  configMode: BRIDGED
---
apiVersion: security.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: prod
  workspace: app-e-ws
  name: app-e-security-group
spec:
  displayName: AppE_SecurityGroup
  namespaceSelector:
    names:
      - "*/ns-e"
  configMode: BRIDGED
---
apiVersion: traffic.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: prod
  workspace: app-f-ws
  name: app-f-traffic-group
spec:
  displayName: AppF_TrafficGroup
  namespaceSelector:
    names:
      - "*/ns-f"
  configMode: BRIDGED
---
apiVersion: security.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: prod
  workspace: app-f-ws
  name: app-f-security-group
spec:
  displayName: AppF_SecurityGroup
  namespaceSelector:
    names:
      - "*/ns-f"
  configMode: BRIDGED
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
Metadata:
  organization: tetrate
  tenant: prod
  workspace: gw-def-ws
  name: gw-def-group
spec:
  displayName: GatewayDEF_Group
  namespaceSelector:
    names:
      - "*/gateway-def"
  configMode: BRIDGED
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: prod
  workspace: gw-tier1-ws
  name: gw-tier1-group
spec:
  displayName: GatewayTier1_Group
  namespaceSelector:
    names:
      - "demo/gateway-tier1"
  configMode: BRIDGED
