---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Tier1Gateway
metadata:
  organization: tetrate
  tenant: prod
  workspace: gw-tier1-ws
  group: gw-tier1-group
  name: gw-tier1-def
spec:
  displayName: AppDEF_Tier1GW
  workloadSelector:
    namespace: gateway-tier1
    labels:
      app: gw-tier1-def
  externalServers:
  - name: def-https
    hostname: def.tetrate.prod
    port: 443
    tls:
      mode: SIMPLE
      secretName: app-def-certs
    clusters:
    - name: active-cluster
