---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-a
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-b
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-c
---
apiVersion: v1
kind: Namespace
metadata:
  name: gateway-abc
