---
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadGroup
metadata:
  name: app-a
  namespace: ns-a
  labels:
    app: app-a
    version: v1
spec:
  template:
    labels:
      app: app-a
      version: v1
    serviceAccount: sa-app-a
    network: virtual-machines
