---
apiVersion: authorization.onboarding.tetrate.io/v1alpha1
kind: OnboardingPolicy
metadata:
  name: allow-app-a-vms
  namespace: ns-a
spec:
  allow:
  - workloads:
    - jwt:
        issuer: "https://issuer-a.tetrate.prod"
    onboardTo:
    - workloadGroupSelector:
        matchLabels:
          app: app-a
          version: v1
