---
apiVersion: authorization.onboarding.tetrate.io/v1alpha1
kind: OnboardingPolicy
metadata:
  name: allow-app-c-vms
  namespace: ns-c
spec:
  allow:
  - workloads:
    - jwt:
        issuer: "https://sample-jwt-issuer.example"
    onboardTo:
    - workloadGroupSelector:
        matchLabels:
          app: app-c
          version: v1
